# Generated by Django 3.2 on 2022-07-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='joke',
            field=models.BooleanField(default=False),
        ),
    ]
