# Generated by Django 3.2 on 2022-07-23 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_joke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='joke',
        ),
    ]
